-- Ejecuta este script en el SQL Editor de tu Dashboard de Supabase

-- 1. Crear Tabla de Salas (Rooms)
CREATE TABLE public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INT NOT NULL,
    type TEXT NOT NULL,
    equipment TEXT,
    "imageUrl" TEXT
);

-- 2. Crear Tabla de Reservas (Bookings)
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roomId" BIGINT REFERENCES public.rooms(id) ON DELETE CASCADE,
    title TEXT,
    start_time BIGINT NOT NULL,
    end_time BIGINT NOT NULL,
    status TEXT NOT NULL,
    requested_by TEXT
);

-- 3. Deshabilitar Seguridad a Nivel de Fila (RLS)
-- Esto permite que nuestro HTML frontend funcione inmediatamente usando el "anon key".
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;

-- 4. Ingresar Datos de Demostración
INSERT INTO public.rooms (name, capacity, type, equipment, "imageUrl") VALUES
('Auditorio Principal (Apolo)', 60, 'type3', 'Sistema de sonido, Streaming 4K, Tarima', 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=800'),
('Sala Ejecutiva Boardroom', 12, 'type2', 'Pantalla OLED 85", Mesa pulida', 'https://images.unsplash.com/photo-1572099351239-2a945b14c330?auto=format&fit=crop&q=80&w=800'),
('Brainstorming Alpha', 6, 'type1', 'Pizarra Interactiva, Soft Seating', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=800');
