-- Tabla para guardar a los usuarios VIP (Administradores Reales)
CREATE TABLE public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE
);

-- Deshabilitar RLS para acceso rápido
ALTER TABLE public.admin_users DISABLE ROW LEVEL SECURITY;

-- Asignarte a ti mismo como el primer administrador supremo
INSERT INTO public.admin_users (username) VALUES ('artez');
