-- =========================================================================
-- ADVERTENCIA: Este script ELIMINARÁ las tablas actuales y todos sus datos.
-- Úsalo solo si quieres hacer un "borrón y cuenta nueva" en tu base de datos.
-- =========================================================================

-- 1. Eliminar tablas existentes (si existen)
DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.rooms CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.admin_users CASCADE; -- Por si quedó de una versión anterior

-- 2. Crear Tabla de Salas (Rooms)
CREATE TABLE public.rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    capacity INT NOT NULL,
    type TEXT NOT NULL,
    equipment TEXT,
    "imageUrl" TEXT
);

-- 3. Crear Tabla de Reservas (Bookings)
CREATE TABLE public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "roomId" BIGINT REFERENCES public.rooms(id) ON DELETE CASCADE,
    title TEXT,
    start_time BIGINT NOT NULL,
    end_time BIGINT NOT NULL,
    status TEXT NOT NULL,
    requested_by TEXT
);

-- 4. Crear Tabla de Roles de Usuario (Admins y Managers)
CREATE TABLE public.user_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    role TEXT DEFAULT 'admin'
);

-- 5. Deshabilitar Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles DISABLE ROW LEVEL SECURITY;

-- 6. Ingresar Datos de Demostración para Salas
INSERT INTO public.rooms (name, capacity, type, equipment, "imageUrl") VALUES
('Auditorio Principal (Apolo)', 60, 'type3', 'Sistema de sonido, Streaming 4K, Tarima', 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&q=80&w=800'),
('Sala Ejecutiva Boardroom', 12, 'type2', 'Pantalla OLED 85", Mesa pulida', 'https://images.unsplash.com/photo-1572099351239-2a945b14c330?auto=format&fit=crop&q=80&w=800'),
('Brainstorming Alpha', 6, 'type1', 'Pizarra Interactiva, Soft Seating', 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&q=80&w=800');

-- 7. Asignarte a ti mismo como el primer administrador (Reemplaza 'artez' por tu usuario si usas otro al entrar)
INSERT INTO public.user_roles (username, role) VALUES ('artez', 'admin');
